### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by juancarloshg** [civicreactor/Meals-on-Wheels#11]
What options should we have in the menu?

I was thinking about adding "admin" or something similar for the management pages, but it probably shouldn't be in the menu. We could have it hidden, something like mealsonwheels.com/admin

Anyway, we need something for the menu, or remove it

**Comment by anna-kondratiuk** [comment]
In my opinion in Menu section should be something simple: 
--> About- will say about the app, and direct to civic reactor 
--> Contact --> contact details to the charity
--> sign in / out
--> help and info (terms and conditions, info about the version, 
--> feedback

Not sure if we want all

**Comment by juancarloshg** [comment]
ok, I will start with those for now
